### PR TITLE
Food items

### PR DESCRIPTION
**Pull request by salamf**
See Picture Below for an example:

Screenshot 2024-03-03 at 3 33 54 PM

You can't really run this unless you modify the code or create a component that calls the FoodCardList component with a list of `meals` (the macro page will call this).

### CODE REVIEW

**Comment by johnmck95** [comment]
Nice, looking good! Couple styling things

1. @mehradadimi setup the `League Spartan` font on other PRs based on our figma design, and they are defined under Fonts in theme.js, its called navbar. That font can be used for titles and sub titles.
2. Is there a follow-up plan to add some colour / themeing to the design?
3. I think we should use _carbohydrates_ rather than _carbs_ from a professional POV
4. Doesn't seem to work in dark mode
image


Let's wait to integrate this with the macro filter and the detail modal before merging

**Comment by salamf** [comment]
> Nice, looking good! Couple styling things
> 
> 1. @mehradadimi setup the `League Spartan` font on other PRs based on our figma design, and they are defined under Fonts in theme.js, its called navbar. That font can be used for titles and sub titles.
> 2. Is there a follow-up plan to add some colour / themeing to the design?
> 3. I think we should use _carbohydrates_ rather than _carbs_ from a professional POV
> 4. Doesn't seem to work in dark mode
> 
> image
> Let's wait to integrate this with the macro filter and the detail modal before merging

Thanks for the feedback!

1. Font updated
2. Not sure, I think it's fine the way it is? Either way, we'll see how it turns out when it's integrated with the Macro Page and then if we need to we can update the colors/themes (for now I made the boxes a very slight grey in light mode, and dark grey in dark mode (see photos below)
3. Changed `Carbs` to `Carbohydrates`
4. Works in Dark mode now!

Screenshots:
Screenshot 2024-03-04 at 11 26 31 AM

Screenshot 2024-03-04 at 11 26 50 AM

**Review by mehradadimi — CHANGES_REQUESTED** [review]
looks good. A couple of comments:

1. The first item is under the navbar, so the new layout changes need to be merged into this branch before this get merged in. Macro Page is in the main now, so merging main into this would be enough 
Screenshot 2024-03-04 at 2 04 24 PM

2. Its better if we change the restaurant name color to be more visible. Also with a bigger font maybe, restaurants are to be seen in this app. 
Screenshot 2024-03-04 at 2 04 55 PM

3. In mobile screen, the card takes the whole page, we can use Chakra UI's property to give sizes to the card for different screen sizes ->  for example, `["md", "md", "lg", "lg"]`
Screenshot 2024-03-04 at 2 05 46 PM

4. The first item should be below the navbar in small screens too, which will be fixed after taking new `layout` changes from te macro page
Screenshot 2024-03-04 at 2 07 21 PM


5. `cursor` needs to be set to `pointer` for cards, so the user get a sense of clicking on it

**Comment by salamf** [comment]
> looks good. A couple of comments:
> 
> 1. The first item is under the navbar, so the new layout changes need to be merged into this branch before this get merged in. Macro Page is in the main now, so merging main into this would be enough
> 
> Screenshot 2024-03-04 at 2 04 24 PM
> 2. Its better if we change the restaurant name color to be more visible. Also with a bigger font maybe, restaurants are to be seen in this app.
> 
> Screenshot 2024-03-04 at 2 04 55 PM
> 3. In mobile screen, the card takes the whole page, we can use Chakra UI's property to give sizes to the card for different screen sizes ->  for example, `["md", "md", "lg", "lg"]`
> 
> Screenshot 2024-03-04 at 2 05 46 PM
> 4. The first item should be below the navbar in small screens too, which will be fixed after taking new `layout` changes from te macro page
> 
> Screenshot 2024-03-04 at 2 07 21 PM
> 5. `cursor` needs to be set to `pointer` for cards, so the user get a sense of clicking on it

1,4,5: Sounds good.
2. I can brighten the restaurant name color but the size is good, anything bigger would not look nice. I tried playing with different sizes and this one looks the nicest.
3. I will make these cards match the width of the navbar.

**Pull request merged**
