### PR TITLE
Detailed Food Modal

### PR DESCRIPTION
**Pull request by johnmck95**
## This MR..
- Makes a new `useMealsById` hook that fetches the in-depth details about a meal
  -  **Warning:** NutritionIX rate limits really hard on this endpoint and you will quickly burn through your API calls. I have added an `IS_TESTING` variable in the food (which i have left true) so that we use dummy data while developing. You can set it to TRUE to get real data based on the specific mea
- Added `"x-remote-user-id": 0,` to the API hooks, again to help nutritionIX track when we are in dev vs prod mode.
- Adds a new `DetailedFoodModalContent` component which populates a ChakraUI modal
  - It consumes the new `NutritionFacts` component that displays a nutrition label
  - It shows the food name, brand and an image
- Uses the `FoodCard` component to test this scenario, which will need to be deleted eventually, but serves as a good example for the time being
- Adds a `LoadingSpinner` to render while content is loading

## How to use..
I decided a modal is the best way to build this detailed food component. That means the caller needs to use all the standard chakraUI tools to make it render, while the component i built is the entire contents to populate the otherwise blank modal.

```
const { meals, loading, error } = useMealsByMacros(desiredMacros); // list of meals
  const [isOpen, setIsOpen] = useState(false); // state of the modal
  const [selectedMeal, setSelectedMeal] = useState(null); // **IMPORTANT** using a selectedMeal avoids your component from rendering 20 detailedmeals to the DOM, which eats up 20 precious detailedMeal fetches, when you only need 1.

// The caller will need to make modal state
  const openModal = (meal) => {
    setSelectedMeal(meal);
    setIsOpen(true);
  };
  const closeModal = () => {
    setSelectedMeal(null);
    setIsOpen(false);
  };

  return (
        <Box>
          {meals.map((meal) => (
            <Box
              key={meal.food_name}
              m="1rem"
              p="1rem"
              border="2px solid black"
              onClick={() => openModal(meal)}   // Open the modal when the specific meal is clicked 
            >
              <Heading fontSize="xl">{meal.food_name}</Heading>
            </Box>
          ))}
          {selectedMeal && (
            <Modal isOpen={isOpen} onClose={closeModal}>
              <ModalOverlay />
              <ModalContent w="90%" h="90%">
                <DetailedFoodModalContent
                  meal={selectedMeal}
                  onClose={closeModal}
                />
              </ModalContent>
            </Modal>
          )}
        </Box>

  );
```

### Demo

https://github.com/SENG480a-NutriDine/webapp/assets/76227136/49ab5931-277c-4012-872b-91660e404b0e

### CODE REVIEW

**Review by mehradadimi — DISMISSED** [review]
Looks really good! Good job man. A few comments. 

1. The first item is not clickable, and that is because of the NavBar. This bug has been fixed in my Macro Page PR, so it might be worth it to merge those stuff into this branch.Screenshot 2024-03-03 at 1 12 46 PM
2. Im pretty sure we wont use these cards to display (the items, not the detailed card), but the cursor on the cards are not set as `pointer`, so it does not feel like you need to click on it. But we wont use these cards so its fine, just wanted to mention
3. I have been using the `League Spartan` font on other PRs based on our figma design, and they are defined under Fonts in `theme.js`, its called `navbar`. That font can be used for titles and sub titles.
4. The title looks a bit big to me in mobile, but feel free to choose whatever you think looks fine. The `X` button can be bolder, and moved to the right a bit, if possible
Screenshot 2024-03-03 at 1 17 48 PM


Overall, it looks great!

**Comment by johnmck95** [comment]
> Looks really good! Good job man. A few comments.
> 
> 1. The first item is not clickable, and that is because of the NavBar. This bug has been fixed in my Macro Page PR, so it might be worth it to merge those stuff into this branch.Screenshot 2024-03-03 at 1 12 46 PM
> 2. Im pretty sure we wont use these cards to display (the items, not the detailed card), but the cursor on the cards are not set as `pointer`, so it does not feel like you need to click on it. But we wont use these cards so its fine, just wanted to mention
> 3. I have been using the `League Spartan` font on other PRs based on our figma design, and they are defined under Fonts in `theme.js`, its called `navbar`. That font can be used for titles and sub titles.
> 4. The title looks a bit big to me in mobile, but feel free to choose whatever you think looks fine. The `X` button can be bolder, and moved to the right a bit, if possible
> 
> Screenshot 2024-03-03 at 1 17 48 PM
> Overall, it looks great!

1. Merged your macro branch in and it fixed up the issue. I made some refactors regarding the hook and fetch process and all is working. This has all the latest changes from https://github.com/SENG480a-NutriDine/webapp/pull/8 
2. Correct, the `FoodCard.js` is just a garbage component i made to test the db hook, and now to open the detailed food modal. Once we get @salamf 's food component merged in and loading the detailed food modal we can delete FoodCard.js
3. Thanks for the tip, fonts have been updated
4. Title has been made smaller, let me know your thoughts

Additionally, I restyled the scroll functionality, the `X` in the top right corner, and made the navbar icons have a little more padding
### 
New Demo:

https://github.com/SENG480a-NutriDine/webapp/assets/76227136/acb56110-c718-4a87-9865-4c02b06e578c

**Review by salamf — COMMENTED** [review]
Amazing work John! Its looking really nice.

I just have a few styling opinions:

1. I don't think having an `X` AND a `close` button on the modal is necessary (especially since a user can also just click anywhere on the screen to close the modal), its essentially just two ways of doing the same thing.

2. If we're going to keep the `X` button then I think it would be a lot nicer if it aligned with the heading at the top (see picture below).
image

3. If we're going to keep the `close` button, I think it would be a lot nicer if we align it such that it ends where all the rest of the content ends (see picture below).
image

**Comment by johnmck95** [comment]
> Amazing work John! Its looking really nice.
> 
> I just have a few styling opinions:
> 
> 1. I don't think having an `X` AND a `close` button on the modal is necessary (especially since a user can also just click anywhere on the screen to close the modal), its essentially just two ways of doing the same thing.
> 2. If we're going to keep the `X` button then I think it would be a lot nicer if it aligned with the heading at the top (see picture below).
>    image
> 3. If we're going to keep the `close` button, I think it would be a lot nicer if we align it such that it ends where all the rest of the content ends (see picture below).
>    image

Good call, thanks Salam! I deleted the 'Close' button and re-aligned the `X`

image

image

**Review by salamf — COMMENTED** [review]
Thanks for fixing the `x` button!

One other thing I just noticed is the following:

On dark mode, wouldn't it be nicer if the color of the `x` button was the same color as the accent color of the Navbar?

like for example in light mode, the `x` button color is green and so is the navbar selection color, so it would make sense to make them the same in dark mode too (see picture below).
Screenshot 2024-03-04 at 10 26 24 AM

What do you think?

**Comment by johnmck95** [comment]
> ight mode, the `x` button

Yeah, it definitely would be nice. Problem is there is very little contrast with the background. Personally, I think we should get this in, then integrate it with your MR and get your changes in, then once the major features are in, we can address these stylistic problems, especially since the themeing is not well defined in the project yet

image

**Comment by salamf** [comment]
> > ight mode, the `x` button
> 
> Yeah, it definitely would be nice. Problem is there is very little contrast with the background. Personally, I think we should get this in, then integrate it with your MR and get your changes in, then once the major features are in, we can address these stylistic problems, especially since the themeing is not well defined in the project yet
> 
> image

Good call! Yeah I agree, this PR is looking good for me, I will approve it

**Review by salamf — APPROVED** [review]
Looking good to me! Really good work on this PR @johnmck95!!

**Comment by johnmck95** [comment]
> Looking good to me! Really good work on this PR @johnmck95!!

Thanks Salam! Let me know when you need a review on yours, I'll be around today and will try to speed up the process for you asap

**Pull request merged**
