### PR TITLE
Simple Profile page

### PR DESCRIPTION
**Pull request by mehradadimi**
If we have a design in mind, we can update this!

https://github.com/SENG480a-NutriDine/webapp/assets/83256092/f69f5529-a88d-4285-a4ed-b76227ab437b

### CODE REVIEW

**Review by salamf — COMMENTED** [review]
What do we need to include in the profile page? if its just the nutritional preferences, name, and email, then maybe we can just put the name and email on the nutritional preferences page and make that the profile page?

That way its quicker and simpler for the user to access the nutritional preferences page

**Comment by salamf** [comment]
Another idea I have is maybe to keep the profile page and then maybe just display all the nutritional preferences along with name and email, and then a button 'change preferences' that leads to the change preferences page?

**Comment by mehradadimi** [comment]
> Another idea I have is maybe to keep the profile page and then maybe just display all the nutritional preferences along with name and email, and then a button 'change preferences' that leads to the change preferences page?

That is what I thought too. we can do whatever. Just get this PR in and you can change the styling or anything else later if you want.

**Comment by johnmck95** [comment]
Nice, looks good Mehrad and love to see the menu goes away when you click the profile! 

I think there was one edge case that got missed here. When you are logged in, clicking a menu item usually closes the menu and takes you to the corresponding page, but that doesn't occur when you're on mobile or a small device (when the navbar switches to vertical). You can see it takes you to the profile page when you're signed out, just not when you're signed in


https://github.com/SENG480a-NutriDine/webapp/assets/76227136/a7ce6494-e69f-47c0-ada5-e6800c71b314

**Comment by salamf** [comment]
> Nice, looks good Mehrad and love to see the menu goes away when you click the profile!
> 
> I think there was one edge case that got missed here. When you are logged in, clicking a menu item usually closes the menu and takes you to the corresponding page, but that doesn't occur when you're on mobile or a small device (when the navbar switches to vertical). You can see it takes you to the profile page when you're signed out, just not when you're signed in
> 
>  2024-03-30.15-31-40.mp4

This seems to be happening because your screen is small, so the menu that appears when you open the profile dropdown menu is hidden under the screen. Making the navbar fit smaller screens should probably be addressed in a seperate PR.

This is how it looks like on my screen for reference:

https://github.com/SENG480a-NutriDine/webapp/assets/68176524/2f19dba8-78e6-4d6a-a5fb-c446f97e8129

**Review by salamf — APPROVED** [review]
NavBar on smaller screen sizes should probably be addresses in another PR.

Other than that I guess its good to get this PR merged in for.

**Pull request merged**
