### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by mehradadimi**
Icons added to filters, based on whatever I could find

### CODE REVIEW

**Review by salamf — CHANGES_REQUESTED** [review]
1. It makes the filters too close the food items.

2. the food items are not the same width anymore

before:
Screenshot 2024-04-11 at 5 12 05 PM

after:
Screenshot 2024-04-11 at 5 12 31 PM

**Comment by mehradadimi** [comment]
> 1. It makes the filters too close the food items.
> 2. the food items are not the same width anymore
> 
> before: Screenshot 2024-04-11 at 5 12 05 PM
> 
> after: Screenshot 2024-04-11 at 5 12 31 PM

The absolute positioning makes it hard to apply that change, needs to change many things for that. If you want, feel free to make it aligned! Im done with my changes

**Comment by salamf** [comment]
Maybe if we justify="space-between" the icons and text it would be nicer?

And maybe increase the width of the top box as well so their widths become equal again.

**Comment by mehradadimi** [comment]
> Maybe if we justify="space-between" the icons and text it would be nicer?
> 
> And maybe increase the width of the top box as well so their widths become equal again.

All yours brother, i couldnt fix it

**Comment by salamf** [comment]
Looks better without the icons if it ruins the aligning

**Pull request closed without merging**
