### PR TITLE
Nutrient Preferences Form

### PR DESCRIPTION
**Pull request by johnmck95**
### Description
This form collects the personal maximum values for all the macro & micronutrients, which are then displayed on the `Nutrition Facts` label. This includes the micronutrient **Watch List**. It validates the format of all inputs, but also allows null submissions - in this case, the user gets the default 2000 calorie/day recommendations by the FDA.

This form is now shown both during the Sign Up process and on the user profile.

A new firebase `firestore` DB has been created, as well as a hook to write to the DB. This hook first tries to find the doc based on userUid. If the doc is found it is updated; if there is not a NutrientPreference doc for the specific user, it will make a new one.

The Nutrition Facts component now fetches this information from the DB, and auto-updates based on user preferences, and always shows the watchlist nutrients, even if there is no data on them.

## Screen grabs
image
image
image

### CODE REVIEW

**Review by mehradadimi — CHANGES_REQUESTED** [review]
Great job @johnmck95 ! It looks great!

A few things to mention:

1) All other pages prior to the Maximus page are left aligned. It is better to aligned the text to the left to be consistent
2) The fonts look a bit big to me, also  it would be great to have some distance between the title and the description.
Screenshot 2024-03-22 at 1 23 43 PM

3) The Selected Nutrient Maximum comes up as an array or sth with indexes being the nutrient. I think it's better to have an indicator for each of them, something like a dictionary
Screenshot 2024-03-22 at 1 27 33 PM

**Comment by johnmck95** [comment]
> Great job @johnmck95 ! It looks great!
> 
> A few things to mention:
> 
> 1. All other pages prior to the Maximus page are left aligned. It is better to aligned the text to the left to be consistent
> 2. The fonts look a bit big to me, also  it would be great to have some distance between the title and the description.
> 
> Screenshot 2024-03-22 at 1 23 43 PM
> 3. The Selected Nutrient Maximum comes up as an array or sth with indexes being the nutrient. I think it's better to have an indicator for each of them, something like a dictionary
> 
> Screenshot 2024-03-22 at 1 27 33 PM

@mehradadimi I've updated the styling based on 1 and 2, let me know your thoughts! 

image
image

3. Is working as intended - the `0`, `1`... is just the array index assigned by Firebase. Each array entry is an object (key-value pair) mapping the id (primary key) to the user's choice. It looks weird in firebase due to the explicit index being mentioned, but that layout is by design

**Review by mehradadimi — DISMISSED** [review]
Thanks for the updated @johnmck95 . Looks much better. A couple of things I noticed:

1. The titles looks a bit big on phone screens, compared to the text below them. Maybe we can specify different sized for different screens?
Screenshot 2024-03-25 at 9 18 24 PM
2. I tried adding the character `e` in the number inputs, and it still updated the profile with those values successfully. Ideally, we only want numbers for those fields. 
3. Let's also make the font sizes consistent. Maybe the same size for the dropdown text and the description?

Screenshot 2024-03-25 at 9 21 07 PM

**Comment by johnmck95** [comment]
Mind if I address this in a follow up PR?

**Review by salamf — APPROVED** [review]

**Pull request merged**
